name: learn-github-actions
on:
  push:
    branches:
      - 'dev'
jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: ./.github/workflows/actions/github-actions.yml
        with:
          server: newtype.solutions
          username: kareembh@newtype.solutions
          password: Ghfy1992
#           protocol: ftps
          server-dir: /public_html/dev.newtype.solutions/



