name: learn-github-actions
on:
  push:
    branches:
      - 'dev'
jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        uses: actions/setup-node@v2

      - name: 📂 Sync files
        uses: ./
        with:
          server: kareembh@newtype.solutions
          username: kareembh@newtype.solutions
          password: 'Ghfy1992'
          protocol: ftps



